### ISSUE TITLE
Class MageSuite\ContentConstructorFrontend\Service\MediaResolver contains 1 abstract method and must therefore be declared abstract or implement the remaining methods 

### ISSUE THREAD

**Issue by rensvw** [magesuite/magesuite#103]
Hi, I've got the following error when upgrading the creativestyle/magesuite-content-constructor package from v2.0.6 to v2.0.7.
I am running magento 2.3.7

Fatal error: Class MageSuite\ContentConstructorFrontend\Service\MediaResolver contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (MageSuite\ContentConstructor\Service\MediaResolver::resolveSrcSetArray) in /var/www/magento/vendor/creativestyle/magesuite-content-constructor-frontend/Service/MediaResolver.php on line 5

I've implemented the following method in the MediaResolver class to fix the issue:

public function resolveSrcSetArray($array){
        return $array;
  }

**Comment by diwipl** [comment]
Hi, 

Thank you for submitting your issue.

We're aware and are working on a fix.

**Comment by rensvw** [comment]
Thanks

**Comment by blanioo** [comment]
Hello @rensvw 

Fix is applied and new tag is released
