### ISSUE TITLE
Unlock new creativestyle/theme-creativeshop versions

### ISSUE THREAD

**Issue by fritzmg** [magesuite/magesuite#106]
When using the `creativestyle/magesuite` you are currently stuck with version `12.x` of the `creativestyle/theme-creativeshop` Magento theme. However, there is now version `13.x`, `14.x` and `15.x` available (not sure why so many major versions in quick succession?). Version `12.x` has some severe problems with Safari for example that are fixed in `13.x` and higher as far as I know. For instance the off canvas cart does not work at all with Safari. This is what it looks like when the mini cart overlay is supposed to be closed:

![image (1)](https://user-images.githubusercontent.com/4970961/132487424-44b6d398-1e1c-4b23-a7b1-7323f91f78f1.png)

And this is how it looks like when it is supposed to be open:

![image (2)](https://user-images.githubusercontent.com/4970961/132487463-b62567b8-ef2c-4b28-84f3-24d77b802577.png)

Part of the problem is the usage of the `will-change` CSS directive on certain elements which will cause this misbehaviour in Safari. These usages of `will-change` have been removed in the newer versions of the theme.

So are there any plans to unlock MageSuite for the new theme versions?

**Comment by diwipl** [comment]
We have done this yesterday, and I've just changed default branch to 9.x:

https://github.com/magesuite/magesuite

**Comment by fritzmg** [comment]
Oh, haha, I did not notice, thank you :)
