### ISSUE TITLE
change related products title

### ISSUE THREAD

**Issue by onsite12** [magesuite/magesuite#108]
Hello, 

I tried changing the related products title on the product page, but I can't get it to change. 
![image](https://user-images.githubusercontent.com/82204564/134008649-de31a487-a4ab-49a5-ad24-dce195d1cdb5.png)

I have tried putting a CSV file on Vendor/theme/i18n/nl_NL.csv 
After flushing and clearing it still show old title. 

How can I solve this?

**Comment by ggm-dev** [comment]
Hi - Can you show a line of your csv?  Translations work for me in vendor/creativestyle/mychildtheme/src/i18n/en_US.csv with following format:

"Acquire your gift now!","Get your FREE GIFT from Our Store!", module, MageSuite_CartBonus
"Related products","You might like these!", module, Magento_Catalog

When theme is built it writes to app/design/frontend/creativestyle/mychildtheme/i18n/en_US.csv

David

**Comment by onsite12** [comment]
Hi, 

I have done it like this: Related Products,"Gerelateerde producten",module,Magento_Catalog
The file is put in: /public_html/vendor/creativestyle/theme-creativeshop/i18n/nl_NL.csv without any result. 

After deploying content it does not get build in app/design/frontend/creativestyle/mychildtheme/i18n/
I can't find any files in there.

**Comment by ggm-dev** [comment]
Are you putting the csv in vendor/creativestyle/theme-creativeshop or in your child theme?  Also, check that your path matches the one I listed - Your example is missing 'src' directory.

**Comment by mborkowski** [comment]
Translation strings are case sensitive. Original string is "Related products" (2nd word starts with lowercase "p").

**Comment by onsite12** [comment]
I have moved the folder the /src (/public_html/vendor/creativestyle/theme-creativeshop/src/i18n) I have flushed cache and reindexed without any changes. I also checked and added related products with lowercase "P" instead of uppercase without any luck. 

Any other suggestions?

**Comment by drabikowy** [comment]
theme-creativeshop needs to be build and  output should land in app/design/frontend/... 
the same as themes that inherits it. If it does not happen, I think sth is wrong in the architecture. 
And this does not seem like issue in Magesuite itself. I'm closing the issue. 

Best regards
