### ISSUE TITLE
Dependency on smile/elasticsuite 2.7.*

### ISSUE THREAD

**Issue by Judder** [magesuite/magesuite#11]
Magento 2.3+ removes Magento\CatalogInventory\Model\Plugin\Layer which means you need to upgrade to Smile Elastic 2.8 as this fixes the dependency

Magesuite requires Smile Elastic 2.7 in it's composer file, so trying to do the above upgrade causes a minimum-stability conflict

**Comment by krisdante** [comment]
We work with Magento 2.3.1 and Magesuite so there is something wrong with this asumption about 2.3+

**Comment by Judder** [comment]
It's Magento ver. 2.3.2 only

**Comment by stoutik** [comment]
I have the same Problem, i use Magento 2.3.1 and Smile Elastic 2.8.1.
I had a problem with Smile Elastic 2.7 :   https://github.com/Smile-SA/elasticsuite/issues/1433

![image](https://user-images.githubusercontent.com/10999921/61717505-7e113280-ad61-11e9-8894-ba3318534b55.png)

**Comment by diwipl** [comment]
I will adjust versions of elasticsuite today.

**Comment by Judder** [comment]
Great - still the same dependency errors today so guess still waiting for the updates?

**Comment by diwipl** [comment]
Yes, I was not able to do it yet, 100% I will have time to do it tomorrow

**Comment by diwipl** [comment]
We're having some issue with our Jenkins job to synchronise contents of our gitlab with github, after resolving it tomorrow newest changes should be pushed.

**Comment by diwipl** [comment]
Release 3.0.0 is now on github, it bumps up dependency on elasticsuite to 2.8.*

**Comment by vicobohdan** [comment]
Hi. Seems there is bug. If I try compile/or setup:upgrade magento, shows error: 

`PHP Fatal error:  Interface 'Smile\ElasticsuiteCatalog\Model\Layer\Filter\FilterInterface' not found in /var/www/vendor/creativestyle/magesuite-brand-management/Model/Layer/Filter/Attribute.php on line 8`

May you check it pls?

installed version of packages:
creativestyle/magesuite v3.0.0
smile/elasticsuite 2.8.1
