### ISSUE TITLE
Content Constructor: product teaser module not showing up

### ISSUE THREAD

**Issue by phellwig92** [magesuite/magesuite#110]
When I add the product teaser module via the content constructor to a page and add an SKU, nothing is showing up on the frontend. No html container nothing. Other product modules are working (so the SKU is not the problem). We are using Magento 2.4.2

**Comment by mborkowski** [comment]
Hi @phellwig92,
We will no longer develop this feature, product teaser component will be removed in upcoming versions.
Instead we are planning to introduce Custom Content Constructor Components so that everyone can create any component he needs for his project
