### ISSUE TITLE
Thumbnail Gallery not working

### ISSUE THREAD

**Issue by racing-cars** [magesuite/magesuite#112]
Hi 

The thumbnail gallery has incorrect formatting. The thumbnail are above instead under and mouse over not working.
![example gallery picture](https://user-images.githubusercontent.com/55644681/154201818-92056b27-b054-46ea-83bb-11c06260eec5.PNG)

I know it working with old Version, now with Magento 2.4.2 the issue is .  Magesuite 9.0.0

**Comment by mborkowski** [comment]
Hi @racing-cars 
Screenshots without stack info are not telling much. Do you have custom theme? How it was created and customized? Can you provide some URL for me to check it?

**Comment by racing-cars** [comment]
Hi @mborkowski 

URL: [racing-cars.ch](https://racing-cars.ch)
Thumbnail Gallery is disabled at moment. Please tell me, if you want see with Thumbnail Gallery activated, so can enable shortly.
I thinking it is standard magesuite theme and no customized.

Thanks.

**Comment by mborkowski** [comment]
Maybe I misunderstand, but isn't this issue about image gallery on PDP? Because I don't see any problems there

**Comment by racing-cars** [comment]
@mborkowski Now you can see. I have enabled.

**Comment by mborkowski** [comment]
Thanks for this report. I've created internal ticket, however I'm not sure when it's going to be fixed (and if it will be patched to 9.0^. This regression happened because of performance improvements we recently introduced. 
In case you really need this feature you'd have to create your own theme on top of theme-creativeshop and restore `tile-gallery` component in all entires (`src/entires`) it's commented out.

**Comment by racing-cars** [comment]
Thanks very mutch. For the moment I will disable the feature. Let me know if I can support anything.

**Comment by drabikowy** [comment]
Hello. As mborkowski stated, this tile-gallery component has been commented out in imports. But it can be imported in child theme by overriding/extending entries. Then it should work as before.
In general we started to cut out components which are not must haves - to reduce js/css bundles.

Best regards
