### ISSUE TITLE
MageSuite v10 does not deliver the correct creativestyle/theme-creativeshop ^16.0.0

### ISSUE THREAD

**Issue by tim-breitenstein-it** [magesuite/magesuite#113]
https://github.com/magesuite/magesuite/blob/10.x/docs/breaking_compatibility_9_to_10.md

> MageSuite 10.0.0 bumps up te following modules:
> 
> theme-creativeshop to version ^16.0.0

The default branch v10.x contains the `"creativestyle/theme-creativeshop": "^16.0.0"` as required dependency: 

https://github.com/magesuite/magesuite/blob/10.x/composer.json

But the MageSuite Tag v10.0.0 contains the `"creativestyle/theme-creativeshop": "^15.0.0"` as required dependency: 

https://github.com/magesuite/magesuite/blob/v10.0.0/composer.json

**Comment by drabikowy** [comment]
Hello @tim-breitenstein-it
It was indeed a mistake in (not) tagging this important commit.  
Sorry for that. 
verison 10.1.0 has been released that corrects this.
 
Please refer to this comment and linked documentation for breaking compatibility description: 
https://github.com/magesuite/magesuite/issues/118#issuecomment-1165697101

**Comment by drabikowy** [comment]
Thanks for pointing this out 🙇🏻
