### ISSUE TITLE
Packagist.org shows theme-creativeshop v15 for v10.0.0 of magesuite

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/magesuite#118]
Hi all - I was troubleshooting an issue with Amazon Pay and noticed that the code was updated in v16 of theme-creativeshop but those changes were not reflected in my install.    I'm running magesuite v10 and composer.json shows dependency of v16.  

    "creativestyle/theme-creativeshop": "^16.0.0",

But in packagist.org, it still shows v15.  
https://packagist.org/packages/creativestyle/magesuite#v10.0.0

I see that v10.x-dev shows v16 of theme-creativeshop.  

Is this correct?

**Comment by ggm-dev** [comment]
Just to follow up here - does the @magesuite team and @diwipl recommend that we use the 10.x-dev branch if we need to use theme-creativeshop v16?  

Thanks!
David

**Comment by diwipl** [comment]
I asked internally our FE devs to check if this is just some fluke on our side that tag was not created or is it on purpose

**Comment by drabikowy** [comment]
Hello @ggm-dev. It was a mistake indeed. 
Version 10.0.0 of MageSuite had dependency to theme-crativeshop v15 what is wrong, as v16 contains needed changes. I prepared breakinig compatibilty description, but it was also not included by mistake. 
I've corrected it just now and released tag 10.1.0. 
Please check it out and refer to this doc for description of the changes that have been introduced in v10 of MageSuite:  
https://github.com/magesuite/magesuite/blob/10.x/docs/breaking_compatibility_9_to_10.md

**Comment by drabikowy** [comment]
And of course, thank you for pointing that out @ggm-dev!

**Comment by tim-breitenstein-it** [comment]
When will version 10.1.0 be released on Packagist.org?

**Comment by drabikowy** [comment]
@tim-breitenstein-it 
Somethng did not click with the webhook, it is available now. 
https://packagist.org/packages/creativestyle/magesuite
