### ISSUE TITLE
Add content in admin

### ISSUE THREAD

**Issue by jacoweb** [magesuite/magesuite#15]
Magento 2.3.2
Elasticsuite 2.8.1
magesuite 3.0

I cant add content in admin. When i try to add any element, i get this error in console:

`content-constructor.ts:314 Uncaught TypeError: Cannot read property 'defaults' of undefined
    at VueComponent.getComponentConfigurator (content-constructor.ts:314)
    at VueComponent.<anonymous> (vue.js:220)
    at VueComponent.onPickComponent (component-picker.ts:115)
    at VueComponent.onPickComponent (vue.js:220)
    at VueComponent.eval (eval at Lt (vue.js:2859), <anonymous>:3:15)
    at HTMLAnchorElement.n (vue.js:8250)
    at HTMLAnchorElement.<anonymous> (vue.js:5047)`

**Comment by jacoweb** [comment]
anyone?

**Comment by diwipl** [comment]
Please check if Theme creativeshop is set in Content -> Design -> Configuration.

It must look like this:
![image](https://user-images.githubusercontent.com/3406741/63048402-c510c480-bed6-11e9-8df2-3d9a6592ee70.png)

**Comment by jacoweb** [comment]
oh! Now its working! :) Thanks!

**Comment by senzulabs** [comment]
Hi @diwipl 
I am not planning to use the Creativeshop theme (or any child Theme) for my webite.
But from your comment, it looks like the only way to get the issue fixed is to use the Creativeshop. Is that correct?
Thanks

**Comment by diwipl** [comment]
Yes, or override logic from this class https://github.com/magesuite/content-constructor-admin/blob/1.x/DataProviders/ContentConstructorConfigDataProvider.php to get contents of etc/view.json from some other place.

**Comment by senzulabs** [comment]
that's exactly what I was looking for, thanks

**Comment by koria** [comment]
Hi @diwipl 

I have same error on fresh server
Magento 2.4.1
php 7.4

![image](https://user-images.githubusercontent.com/61142147/98110962-96e71e00-1ea8-11eb-8ae6-a6ac81c30d3e.png)

Composer:
```
    "version": "2.4.1",
    "require": {
        "creativestyle/magesuite": "^6.0.0",
        "magento/product-community-edition": "2.4.1",
        "smile/elasticsuite": "^2.10"
    },
```

![image](https://user-images.githubusercontent.com/61142147/98111246-f5ac9780-1ea8-11eb-863a-40c28d37b565.png)

what am I doing wrong now in this case?

**Comment by koria** [comment]
When i open Content Constructor first error is

```
content-constructor.js:1361 Uncaught TypeError: Cannot read property 'length' of undefined
    at VueComponent.sortComponentsBySections (content-constructor.js:1361)
    at VueComponent.sortComponentsBySections (vue.min.js:6)
    at VueComponent.ready (content-constructor.js:1136)
    at VueComponent.t._callHook (vue.min.js:6)
    at VueComponent.e (vue.min.js:7)
    at VueComponent.i (vue.min.js:7)
    at VueComponent.t.$emit (vue.min.js:7)
    at VueComponent.t._callHook (vue.min.js:6)
    at s (vue.min.js:6)
    at Array.forEach (<anonymous>)
```

**Comment by backendorf** [comment]
Hi! From what I tested here, the problem @koria  commented on is because the single store mode is active. It is a bug...

**Comment by KhaledBinAmir** [comment]
> Hi @diwipl
> 
> I have same error on fresh server
> Magento 2.4.1
> php 7.4
> 
> ![image](https://user-images.githubusercontent.com/61142147/98110962-96e71e00-1ea8-11eb-8ae6-a6ac81c30d3e.png)
> 
> Composer:
> 
> ```
>     "version": "2.4.1",
>     "require": {
>         "creativestyle/magesuite": "^6.0.0",
>         "magento/product-community-edition": "2.4.1",
>         "smile/elasticsuite": "^2.10"
>     },
> ```
> 
> ![image](https://user-images.githubusercontent.com/61142147/98111246-f5ac9780-1ea8-11eb-863a-40c28d37b565.png)
> 
> what am I doing wrong now in this case?

Hi,
How did you resolved this?

I have same issue with Fresh Magento 2.4.1 installation.

Thanks
