### ISSUE TITLE
Cannot read property 'this.ccConfig.sections.defaults'  of undefined

### ISSUE THREAD

**Issue by achourey** [magesuite/magesuite#27]
After configuring Magesuite on Magento 2.3.2, On add/edit cms page when I click on any component (like "Button") to add any component then it shows an error "Cannot read property 'this.ccConfig.sections.defaults'  of undefined" at line number 316 in "pub/static/version1573823293/adminhtml/Magento/backend/en_US/src/content-constructor.ts". Please see attached screenshots
![magesuite issue](https://user-images.githubusercontent.com/52207120/68946871-07011d80-07da-11ea-9b97-d96a21f369f6.png)
. But when I check this file in the "pub/static/adminhtml/Magento/backend/en_US/src/" directory then I could not find "src" directory under ""pub/static/adminhtml/Magento/backend/en_US/".

Thanks for your support.

**Comment by krzksz** [comment]
Please check https://github.com/magesuite/magesuite/issues/15 for the solution.

**Comment by achourey** [comment]
Great, It is working now. Thanks a lot Friend :)
