### ISSUE TITLE
Your requirements could not be resolved

### ISSUE THREAD

**Issue by joecarder1** [magesuite/magesuite#29]
When following the setup procedures listed in the README I get the following error 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: smile/elasticsuite[2.7.x-dev, 2.8.3].
    - Can only install one of: smile/elasticsuite[2.8.3, 2.7.x-dev].
    - Can only install one of: smile/elasticsuite[2.7.x-dev, 2.8.3].
    - creativestyle/magesuite v2.0.3 requires smile/elasticsuite 2.7.* -> satisfiable by smile/elasticsuite[2.7.x-dev].
    - Installation request for creativestyle/magesuite ~2.0.3 -> satisfiable by creativestyle/magesuite[v2.0.3].
    - Installation request for smile/elasticsuite (locked at 2.8.3, required as ~2.8.0) -> satisfiable by smile/elasticsuite[2.8.3].

Looks like magesuite 2.0.3 is requiring elasticsuite 2.7 but Smile-SA is that I have to use elasticsuite 2.8 or better since I'm running Magento 2.3 please advise.

Thanks!

**Comment by marcelomartinsIT** [comment]
Hello,
You need to install magesuite 3.0
You can change the branch on the top left corner.

Or try to run this command:
`composer require creativestyle/magesuite ^3.0.0`

I also recommend you to have elasticsuite properly setup, makes things easier.

Let me know if worked out!

**Comment by joecarder1** [comment]
That worked perfectly, thank you very much for the prompt reply!

**Comment by marcelomartinsIT** [comment]
I've ran myself into the same error sometimes untill I found there was another branch for the latest magento releases.
Also pay attention that MageSuite does not support Magento 2.3.3. Well it does support it, but has problems in the checkout portion (you can't make orders).

**Comment by krisdante** [comment]
Based on the comments I assume the issue is resolved.
