### ISSUE TITLE
Magento 2.3.2 / 2.3.3 Community - Can not add components in admin content constructor due to err

### ISSUE THREAD

**Issue by Mugentoki** [magesuite/magesuite#35]
I've done a fresh installation with both Magento 2.3.2 and 2.3.3 + Sample Data + Magesuite with the latest 3.0 version (^3.0) but Somehow the content constructor in Admin is broken.
It is not possible to add a component as there are typescript errors in content-constructor.ts:327

Versions as statet in composer.lock
> "creativestyle/magesuite-content-constructor": "v2.0.4",
                "creativestyle/magesuite-content-constructor-admin": "v2.11.4",
                "creativestyle/magesuite-content-constructor-asset": "v1.0.1",
                "creativestyle/magesuite-content-constructor-category-page": "^1.0.1",
                "creativestyle/magesuite-content-constructor-frontend": "v2.19.5",

We have an other installation with Magento 2.3.2 running without any problems.
Installed content constructor repositories are as following:
> "creativestyle/magesuite-content-constructor": "v2.0.3",
                "creativestyle/magesuite-content-constructor-admin": "v2.11.0",
                "creativestyle/magesuite-content-constructor-asset": "v1.0.1",
                "creativestyle/magesuite-content-constructor-category-page": "^1.0.1",
                "creativestyle/magesuite-content-constructor-frontend": "v2.19.0",

So probably something brokw in `content-constructor`, `content-constructor-admin` or `content constructor-frontend`?
I've also made a quick diff check for content-constructor.ts file and there are no changes since our last working project with Magesuite, so most probably the problem is not coming from there.

Would be nice if someone can confirm this is not working or I am just doing something stupid wrong.

Also, here's the error:

> Uncaught TypeError: Cannot read property 'defaults' of undefined
    at VueComponent.getComponentConfigurator (content-constructor.ts:327)
    at VueComponent.<anonymous> (vue.js:220)
    at VueComponent.onPickComponent (component-picker.ts:115)
    at VueComponent.onPickComponent (vue.js:220)
    at VueComponent.eval (eval at Lt (vue.js:2859), <anonymous>:3:15)
    at HTMLAnchorElement.n (vue.js:8250)
    at HTMLAnchorElement.<anonymous> (vue.js:5047)

Let me know if you need any additional information
----------------------------------------
Steps to repdoruce:
1. Install Magento 2.3.2 / 2.3.3
2. Install Magento2 Sample Data
3. Install Magesuite ^3.0
4. Log in to admin and go to any Content Constructor area
5. Try to add any component and check the console for error output

**Comment by diwipl** [comment]
Please check: https://github.com/magesuite/magesuite/issues/15

**Comment by Mugentoki** [comment]
Yup, that fixed it
Stupid me...
Only had it set for default store view, but not for the others

Sorry and thanks for the fast answer!
