### ISSUE TITLE
Failing Static Content deploy

### ISSUE THREAD

**Issue by beyondmediadev** [magesuite/magesuite#39]
Hi,

we run on PHP 7.2 and getting this error when compiling static content for our custom theme:

/magento/pub/static/frontend/Creativestyle/theme-test/en_US/css/commons.css" file can't be read. Warning!file_get_contents(/magento/pub/static/frontend/Creativestyle/theme-test/en_US
  /css/commons.css): failed to open stream: No such file or directory

Commons.css doesn't exist in our compiled theme after yarn build. Any idea how we could fix it?

**Comment by krzksz** [comment]
Hi, thanks for using MageSuite!

We have recently resigned from generating both `commons.css` and `commons.js` files as they were degrading performance instead of improving it. Please make sure your `theme-creativeshop` is up to date and that you have no references to those files in your custom modules.

**Comment by beyondmediadev** [comment]
Hi,
thank you for the quick answer. 
We will try to update the parent theme and report back.

On a side note: How do you handle the main repo, how often is it updated? Currently we require "creativestyle/magesuite": "^3.0.0" . Should we handle all the included packages ourself and look what fits best or go with the "one to rule them all". 

Thanks for the great work. As soon as we get rolling we try to provide help with Pullrequests.

**Comment by beyondmediadev** [comment]
Hi, 

we already use the v8.10.2 . 
In theme-creativeshop/src/Magento_Theme/layout/default_head_blocks.xml you still reference the commons.css.

Wrong Tag maybe?

**Comment by beyondmediadev** [comment]
Hi @krzksz ,
we figured it out. In our theme we used frontend builder 2.1.4 because of the sass project alias bug. 

In this version commons.css and js are already deprecated. 

We updated theme-creativeshop and our theme to the latest release of the frontend builder. 
We now have 2 possibilites:
Either we fork theme-creativeshop and update package.json and yarn.lock or we set the new versions into package.json and build new yarn.lock during deployment. 
Anyway we have to remove commons.css (easy) and commons.js shim (kinda meh as we need to override require-js.conf). 

Neither sounds good to be future proof. 
Any ideas? Or do you plan to update theme-creativeshop any time soon?

EDIT: Third possibility: We override require conf and remove common.css in our theme. We then yarn install --force to get the latest verison of frontend builder. I think we will go with this approach.

**Comment by krzksz** [comment]
Thanks for the info, that's super helpful! There seems to be a problem on our side as we've already released theme-creativeshop with such changes some time ago but the repository was not synced to github properly. I'll ping our devops.

**Comment by beyondmediadev** [comment]
@krzksz any ETA for this? I have to decide if we adjust our deployment or wait for the update on theme-creativeshop.

**Comment by krzksz** [comment]
I have contacted devops last week and they commited to fix it in the current sprint which ends on Friday, that's all I can say right now.

**Comment by beyondmediadev** [comment]
Resolved by the update. Thank you.
