### ISSUE TITLE
Empty htmlClass generates exception

### ISSUE THREAD

**Issue by kukoncik** [magesuite/magesuite#41]
Hello
Facing a problem on Magento 2.3.4 + Magesuite v5

```
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 2542
```

A little bit of debugging and figured out that in/vendor/creativestyle/theme-creativeshop/src/Magento_Cms/layout/cms_page_view.xml line 23

`<referenceContainer name="main.content" htmlClass="" />`

generates the issue, adding any string into that empty htmlClass solves the issue.

Can this be included  in repo, or any other solution that solves the issue.

Thank you

**Comment by krzksz** [comment]
Fixed by https://github.com/magesuite/theme-creativeshop/commit/0844fb3f945aaaf01e6ef96a798f5909fea11b9a
