### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by FredericMartinez** [magesuite/magesuite#42]
## Preconditions

* Magento 2.3.4 + Sample data

## Steps to Reproduce:

`$ composer require creativestyle/magesuite ^5.0.0`

## Expected result:

Magesuite install by Composer ok

## Actual result:

```
$ composer require creativestyle/magesuite ^5.0.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - creativestyle/magesuite-translation-center v1.0.1 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.15) does not satisfy that requirement.
```

**Comment by FredericMartinez** [comment]
Severals submodules are not in PHP 7.3, not just `creativestyle/magesuite-translation-center`

Temp fix: 
```
composer require creativestyle/magesuite ^5.0.0 --ignore-platform-reqs
```

**Comment by FredericMartinez** [comment]
> Severals submodules are not in PHP 7.3

* creativestyle/magesuite-translation-center
* creativestyle/magesuite-css-minifier
* creativestyle/theme-creativeshop

**Comment by krisdante** [comment]
Dependency on PHP was removed
