### ISSUE TITLE
bin/magento setup:upgrade

### ISSUE THREAD

**Issue by pawel86k** [magesuite/magesuite#45]
after installing on mageto 2.3.4 I have a problem and execute the command "bin / magento setup: upgrade"

`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.5.1
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1`

**Comment by diwipl** [comment]
Does not seem like issue introduced by MageSuite, more like ElasticSuite issue.
