### ISSUE TITLE
Compatibility with smile/elasticsuite 2.9 (Magento 2.3.5-p1)

### ISSUE THREAD

**Issue by FredericMartinez** [magesuite/magesuite#46]
Hello folks :high_brightness:,

Elasticsuite just released a new version `2.9`

But Magesuite needs `2.8` max:

```
- creativestyle/magesuite v5.0.0 requires smile/elasticsuite 2.8.* -> satisfiable by smile/elasticsuite[2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.x-dev] but these conflict with your requirements or minimum-stability.
```

FYI, I just try to force it to `2.9`, and it seems to work.
But on this test, I used M2 as a headless ecommerce, so I can't check in front-end.

**Comment by michalzimniak** [comment]
@FredericMartinez how did you forced it to work with elasticsuite 2.9?

**Comment by FredericMartinez** [comment]
@michalzimniak 

Dont require `magesuite/magesuite`, check https://github.com/magesuite/magesuite/blob/5.x/composer.json and require all submodules, at the end, you can force to `2.9`

**Comment by michalzimniak** [comment]
Started to work, thanks ;)

**Comment by FredericMartinez** [comment]
PR : https://github.com/magesuite/magesuite/pull/54

**Comment by diwipl** [comment]
PR was merged. I'm closing this issue.
