### ISSUE TITLE
indexer throws error

### ISSUE THREAD

**Issue by davidverholen** [magesuite/magesuite#5]
**Description**:
this error is happening for the category_products and products_category indexers.
It seems to be a bug with magento code generation in the first place. But as long as it is not fixed there it should maybe be fixed here?

It seems that this problem was introduced in magento 2.3.1 when the return type was added to the execute function. While it is a good thing, to have an explicit return type, there is [an open issue with code generation](https://github.com/magento/magento2/issues/22769) when using : self as return type

2.3.0: https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Catalog/Model/Indexer/Category/Product/Action/Full.php#L136

2.3.1: https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Catalog/Model/Indexer/Category/Product/Action/Full.php#L155

**Reproduce**:
1. install magento 2.3.1
2. set deployment mode to developer
3. install magesuite 2.0.1
5. run `bin/magento indexer:reindex`

**Expected**:
indexing processes complete successfully

**Actual**:
An error is displayed

```
Design Config Grid index has been rebuilt successfully in 00:00:01
Customer Grid index has been rebuilt successfully in 00:00:03
Category Products index is locked by another reindex process. Skipping.
PHP Fatal error:  Declaration of MageSuite\Frontend\Model\Indexer\Category\Product\Action\Full\Interceptor::execute(): MageSuite\Frontend\Model\Indexer\Category\Product\Action\Full must be compatible with Magento\Catalog\Model\Indexer\Category\Product\Action\Full::execute(): Magento\Catalog\Model\Indexer\Category\Product\Action\Full in /Users/david.verholen/Projects/freund/magento/generated/code/MageSuite/Frontend/Model/Indexer/Category/Product/Action/Full/Interceptor.php on line 7

Fatal error: Declaration of MageSuite\Frontend\Model\Indexer\Category\Product\Action\Full\Interceptor::execute(): MageSuite\Frontend\Model\Indexer\Category\Product\Action\Full must be compatible with Magento\Catalog\Model\Indexer\Category\Product\Action\Full::execute(): Magento\Catalog\Model\Indexer\Category\Product\Action\Full in /Users/david.verholen/Projects/freund/magento/generated/code/MageSuite/Frontend/Model/Indexer/Category/Product/Action/Full/Interceptor.php on line 7
```

**Comment by williankeller** [comment]
@davidverholen - Possible duplicated issue, please refer: https://github.com/magento/magento2/issues/22769.

**Comment by diwipl** [comment]
Thank you for your report, I've created internal ticket to resolve this issue. 

It looks like it might be possible that we don't need preference on indexer class anymore.
