### ISSUE TITLE
Content Constructor component Mosaic - Undefined index: mobile

### ISSUE THREAD

**Issue by Mugentoki** [magesuite/magesuite#50]
Adding the component "Mosaic" on any page or category throws an exception in frontend.
```
Exception #0 (Exception): Notice: Undefined index: mobile in ../htdocs/vendor/creativestyle/magesuite-content-constructor-frontend/Helper/ComponentVisibility.php on line 50
```
I had a similar error for a different component when I forgot to select the mobile setting. But for mosaic there is no mobile setting. All other settings are selected.

Magento Version: 2.3.4
MageSuite Version: 5.0.0
magesuite-content-constructor: v2.0.4
magesuite-content-constructor-admin: v2.13.2
magesuite-content-constructor-asset: v1.0.2
magesuite-content-constructor-frontend: v2.21.4
magesuite-content-constructor-remove-layout-validation: v1.0.0

**Comment by diwipl** [comment]
Fixed by following commit: https://github.com/magesuite/content-constructor-frontend/commit/78ea9fd66422b42fa69af84386a68ad06e1d02a9
