### ISSUE TITLE
Fatal error: Uncaught Error: Cannot instantiate interface

### ISSUE THREAD

**Issue by dmalik97** [magesuite/magesuite#55]
Hello. I have got this error after install magesuite package via composer (composer require creativestyle/magesuite ^5.0.0) and then bin/magento setup:upgrade:

Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface in /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace: #0 /app/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...') #1 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...') #2 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'stockResolver', 'MageSuite\\Produ...') #3 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('MageSuite\\Produ...', Array, Array) #4 /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Fram in /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

Before install magesuite I have installed elasticsearch (v6.8.10 on localhost:9200) and elasticsuite (v2.8.8).

**Comment by dmalik97** [comment]
I ran bin/magento setup:di:compile and then I got this error:
Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121 Stack trace: #0 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Invento...', Array) #1 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Invento...') #2 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Invento...') #3 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('MageSuite\\Produ...') #4 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('MageSuite\\Produ...') #5 /app/vendor/magento/framework/ObjectManager/Objec in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

**Comment by dmalik97** [comment]
Before I installed magesuite, I had got disabled MSI modules. So now I enable MSI modules and fatal errors disappear, but.. I can't choose creativestyle theme (I haven't got that option to choose in Content -> Configuration and then edit theme).

I checked whether magesuite is installed via composer (composer show -i) and via bin/magento module:status and it is installed.
So what is the problem?
Is magesuite require MSI modules? On my project I have to disable that modules due to other integrations.

**Comment by diwipl** [comment]
Can you check if you have `app/design/frontend/creativestyle` folder ?

If not then you should build theme according to README: https://github.com/magesuite/magesuite#building-theme-creativeshop

**Comment by dmalik97** [comment]
Yes, I focused on solve problem and then I forgot build theme.. okay, so now I can choose theme :) thanks.
..but what about MSI modules? Is it possible to disable that modules when magesuite is enable?

**Comment by diwipl** [comment]
No, some of our classes depend on them.

If you need to disable reservation feature from MSI we have separate module for that: https://packagist.org/packages/creativestyle/magesuite-disable-stock-reservation
