### ISSUE TITLE
Magento 2.4 upgrade

### ISSUE THREAD

**Issue by sunel** [magesuite/magesuite#58]
Any timeline for 2.4 upgrade

**Comment by shrinet** [comment]
Any update?

**Comment by idziakjakub** [comment]
Hi everyone, any news about compatibility with Magento 2.4?

**Comment by diwipl** [comment]
Hi, 

We're at end of QA testing, we will publish new version compatible with 2.4 until end of the week.

**Comment by idziakjakub** [comment]
Great news @diwipl!

**Comment by manikumaran1978** [comment]
Thank you, Waiting.

**Comment by diwipl** [comment]
FYI: Release will happen tomorrow :) sorry for small delay, we're in process of preparation for Polish Meet Magento, thus we had less time last week for other activities.

**Comment by ggm-dev** [comment]
Saw branch 6.0!  Great news - having installing issue:      

- creativestyle/magesuite-frontend v2.4.7 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.

**Comment by diwipl** [comment]
We have just released MageSuite 6.0.0 metapackage version which is compatible with Magento 2.4 and some earlier Magento versions.

> Saw branch 6.0! Great news - having installing issue:

> creativestyle/magesuite-frontend v2.4.7 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.

Can you provide full error log from composer ? magesuite-frontend 2.4.7 is quite old and should not be installed, so most likely core error is somewhere else.

**Comment by ggm-dev** [comment]
Here you go - I wondered why it was trying to install 2.4.7 as well.  


[error-log.txt](https://github.com/magesuite/magesuite/files/5440941/error-log.txt)

**Comment by diwipl** [comment]
Can you also paste your composer.json ?

**Comment by ggm-dev** [comment]
And I'm sorry - that error log is from trying to manually install magesuite/frontend only.  Here's error log after trying to install v 6.0.0 and getting error for minimum stability- I updated composer and tried again. 


[composer.json.txt](https://github.com/magesuite/magesuite/files/5441034/composer.json.txt)

[error-log-new.txt](https://github.com/magesuite/magesuite/files/5441017/error-log-new.txt)

**Comment by diwipl** [comment]
@ggm-dev I think you've tried to download MageSuite until tag was released. This caused to treat 6.x-dev as unstable and have not downloaded it.

Can you try now ? v6.0.0 is published from yesterdays evening

**Comment by ggm-dev** [comment]
Thanks!  That fixed the other issue but looks like there's still an issue:

Problem 1
    - creativestyle/theme-creativeshop v10.1.2 requires creativestyle/magesuite-server-side-swatches 1.x-dev -> satisfiable by creativestyle/magesuite-server-side-swatches[1.x-dev] but these conflict with your requirements or minimum-stability.

Full log:
[compser-error.txt](https://github.com/magesuite/magesuite/files/5445234/compser-error.txt)

**Comment by nandopsilva** [comment]
The same happening here.

**Comment by diwipl** [comment]
I can confirm that this happens when stability is set to "dist".

Seems like we have not catched it during testing because we use dev stability. We'll change that for the future.

Fix is on the way.

**Comment by diwipl** [comment]
Fix was published, please try now

**Comment by ggm-dev** [comment]
Hi - I see that server-side-swatches constraint was fixed, but now when I try to install (on clean install of 2.4 with no sample data) I get the original error starting with: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - creativestyle/magesuite-frontend v2.4.7 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.

I can post full log if needed.    I'm using minimum-stability of stable.

**Comment by diwipl** [comment]
I've tried to install with following composer.json:
[composer.json.txt](https://github.com/magesuite/magesuite/files/5456994/composer.json.txt)

And had no issues using PHP 7.3.22

**Comment by ggm-dev** [comment]
Thanks for help with this.  I was able to install with your composer.json.  In addition I was able to install with my existing composer.json file by manually adding "creativestyle/magesuite": "^6.0.0" to require key and running composer update.  I still have issue running "composer require creativestyle/magesuite ^6.0.0"

Just in case it helps anyone with same issue.

**Comment by thomas7467** [comment]
Hi ggm-dev
Seems that I have same issue as you, when running "composer require creativestyle/magesuite ^6.0.0" on new composer magento 2.4.0 installation.
" _[InvalidArgumentException]
  Could not find a matching version of package creativestyle/magesuite^6.0.0. Check the package spelling, your version co
  nstraint and that the package is available in a stability which matches your minimum-stability (stable)._"
I've tried with 2.4.1 and 2.4.0, same result.
Is there a way to solve that and install the extension?
thank you

**Comment by ggm-dev** [comment]
Try and add a space before ^ and that problem should go away.

**Comment by thomas7467** [comment]
Thank you ggm-dev, works better with the space...but facing now issues due to may PHP version :
Problem 1
    - creativestyle/magesuite-frontend v2.4.7 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.4.3) does not satisfy that requirement.

**Comment by ggm-dev** [comment]
I had same issue running "composer require creativestyle/magesuite ^6.0.0"

However if you manually edit your composer.json file so that the require section looks something like this:

```
    "require": {
        "creativestyle/magesuite": "^6.0.0",
        "magento/product-community-edition": "2.4.1"
    },
```

and then run "composer update" you should be able to install.

**Comment by koria** [comment]
> I had same issue running "composer require creativestyle/magesuite ^6.0.0"
> 
> However if you manually edit your composer.json file so that the require section looks something like this:
> 
> ```
>     "require": {
>         "creativestyle/magesuite": "^6.0.0",
>         "magento/product-community-edition": "2.4.1",
>         "smile/elasticsuite": "^2.10"
>     },
> ```
> 
> and then run "composer update" you should be able to install.

Hi @ggm-dev 

Hello! Does everything work without errors on version 2.4.1?

I installed the fresh version ^6.0.0 on a fresh server with 2.4.1, and I get an error in the buyer's basket and I can't open the buyer in the admin panel.

Thanks!

**Comment by ggm-dev** [comment]
Hi @koria  - I didn't do much testing with 2.4.1 and 6.0.0 - decided to stay with 2.4.0 on our install for now to avoid potential issues and we're close to launch.

**Comment by kkkonrad** [comment]
looks like magento 2.4 is not compatibile with ps/image-optimizer ^1.0 but creativestyle/magesuite-image-optimization require this version, please update creativestyle/magesuite-image-optimization to support ps/image-optimizer ^2.0

**Comment by diwipl** [comment]
I've changed ps/image-optimizer constraint to 2.0 in magesuite-image-optimization package. 

Please let me know if that fixed the issue.

**Comment by kkkonrad** [comment]
thanks, now it works

**Comment by samumaretiya** [comment]
Hey @diwipl ,

I am running into the following issue while setup the project locally.

`Package operations: 93 installs, 0 updates, 0 removals
  - Installing creativestyle/magesuite-google-api (v1.1.5): Downloading (100%)
    Failed to download creativestyle/magesuite-google-api from dist: Could not delete vendor/creativestyle/magesuite-google-api\fa31ea1fa6acbb7ddd44937222e2f0b4:
This can be due to an antivirus or the Windows Search Indexer locking the file while they are analyzed
    Now trying to download from source
  - Installing creativestyle/magesuite-google-api (v1.1.5): Cloning 995ee0b318 from cache


  [RuntimeException]
  Failed to execute git checkout "995ee0b318783e288043ec11a3bd526cb3945a68" -- && git reset --hard "995ee0b318783e288043ec11a3bd526cb3945a68" --

  error: invalid path 'Test/Unit/Service/GeoLocationResolverTest.php '`

Could you please help me how to fix this hurdle.

Thanks in advance.
