### ISSUE TITLE
Product thumbnails are not generated in the right directory

### ISSUE THREAD

**Issue by anthonyhacart** [magesuite/magesuite#6]
**Description**:
The problem occurs when Magento generates (when adding products) or regenerates thumbnails (with bin/magento catalog:image:resize), the thumbnails are in the wrong folder and cause missing images on the shop.

the thumbnails are in the folder pub/media/catalog/product/*catalog/product*/thumbnail instead of pub/media/catalog/product/thumbnail

 **Reproduce**:
 
 1. install magento 2.3.0
 2. install magesuite 2.0.1
 3. add some products
 4. run bin/magento catalog:image:resize
 
 **Expected**:
 ```
pub
├── media
│   ├── catalog
│   │   └── product
│   │       ├── thumbnail
│   │       │   └── [...]
 ``` 
 **Actual**:
 ```
 pub
├── media
│   ├── catalog
│   │   └── product
│   │       ├── catalog
│   │       │   └── product
│   │       │       └── thumbnail
│   │       │           ├── [...]
 ```

**Comment by diwipl** [comment]
Thank you for your issue report.

Currently we do not support bin/magento catalog:image:resize command at all within lazy-resize extension.

**Comment by anthonyhacart** [comment]
Even when I just add products, thumbnails are generated in wrong folder, any solution to that ?


thank for your fast answer

**Comment by diwipl** [comment]
Can you paste here what URL is generated for product image on storefront ?

**Comment by anthonyhacart** [comment]
http://magento2.docker/pub/media/catalog/product/thumbnail/00eb5dbfcc790e0df40e40d1b5e99569/image/260x270/110/80/f/r/fromvsf.png for example

**Comment by diwipl** [comment]
Ok, seems it might be an issue with `pub/` at the beginning of URL. 

Can you configure your environment to use `pub/` directory as webserver root, and not main magento folder?

**Comment by anthonyhacart** [comment]
That was the problem, thank you.

Sorry for the unnecessary issue.

**Comment by diwipl** [comment]
No problem, anyway since some users had issues with lazy-resize extension we will drop it's usage in open source version of MageSuite.
