### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by manikumaran1978** [magesuite/magesuite#60]
We are using php 7.3
unable to install with following error
 Problem 1
    - creativestyle/magesuite v5.0.1 requires creativestyle/theme-creativeshop ^8.0.0 -> satisfiable by creativestyle/theme-creativeshop[v8.0.0, v8.1.0, v8.10.0, v8.10.1, v8.10.2, v8.11.0, v8.11.1, v8.11.2, v8.11.3, v8.11.4, v8.11.5, v8.11.6, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.13.0, v8.13.1, v8.13.2, v8.13.3, v8.13.4, v8.13.5, v8.13.6, v8.13.7, v8.14.0, v8.14.1, v8.14.10, v8.14.11, v8.14.12, v8.14.13, v8.14.2, v8.14.3, v8.14.4, v8.14.5, v8.14.6, v8.14.7, v8.14.8, v8.14.9, v8.2.0, v8.2.1, v8.3.0, v8.4.0, v8.4.1, v8.5.0, v8.5.1, v8.5.2, v8.5.3, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.8.1, v8.9.0, v8.9.1, v8.9.2].
    - creativestyle/magesuite v5.0.0 requires creativestyle/theme-creativeshop ^8.0.0 -> satisfiable by creativestyle/theme-creativeshop[v8.0.0, v8.1.0, v8.10.0, v8.10.1, v8.10.2, v8.11.0, v8.11.1, v8.11.2, v8.11.3, v8.11.4, v8.11.5, v8.11.6, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.13.0, v8.13.1, v8.13.2, v8.13.3, v8.13.4, v8.13.5, v8.13.6, v8.13.7, v8.14.0, v8.14.1, v8.14.10, v8.14.11, v8.14.12, v8.14.13, v8.14.2, v8.14.3, v8.14.4, v8.14.5, v8.14.6, v8.14.7, v8.14.8, v8.14.9, v8.2.0, v8.2.1, v8.3.0, v8.4.0, v8.4.1, v8.5.0, v8.5.1, v8.5.2, v8.5.3, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.8.1, v8.9.0, v8.9.1, v8.9.2].
    - creativestyle/theme-creativeshop v8.13.1 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.13.2 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.13.3 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.13.4 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.13.5 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.13.6 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.13.7 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.0 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.1 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.10 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.11 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.12 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.13 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.2 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.3 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.4 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.5 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.6 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.7 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.8 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/theme-creativeshop v8.14.9 requires creativestyle/magesuite-product-details-reorder ^1.0.0 -> satisfiable by creativestyle/magesuite-product-details-reorder[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - creativestyle/magesuite-product-details-reorder v1.1.1 requires php ~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/magesuite-product-details-reorder v1.1.0 requires php ~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/magesuite-product-details-reorder v1.0.1 requires php ~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/magesuite-product-details-reorder v1.0.0 requires php ~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.9.2 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.9.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.9.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.8.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.8.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.7.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.7.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.6.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.5.3 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.5.2 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.5.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.5.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.4.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.4.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.3.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.2.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.2.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.13.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.12.3 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.12.2 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.12.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.12.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.11.6 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.11.5 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.11.4 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.11.3 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.11.2 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.11.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.11.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.10.2 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.10.1 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.10.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.1.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - creativestyle/theme-creativeshop v8.0.0 requires php ~5.6.0|7.0.2|~7.0.6|~7.1.0|~7.2.0 -> your PHP version (7.3.21) does not satisfy that requirement.
    - Installation request for creativestyle/magesuite ^5.0 -> satisfiable by creativestyle/magesuite[v5.0.0, v5.0.1].

**Comment by sunel** [comment]
Do this to fix the issue for now

https://github.com/magesuite/product-details-reorder/issues/1

**Comment by diwipl** [comment]
Dear @manikumaran1978 

Thank you for posting your issue.

I've checked product-details-reorder repository and seems we have not tagged code that removed PHP constraint. I've created tag and pushed it to github, so now that extension should be possible to be installed on PHP >= 7.3

**Comment by jtomaszewski** [comment]
Yeah, since https://packagist.org/packages/creativestyle/magesuite-product-details-reorder#v1.1.2 is published, this issue is resolved now. (The issue can be closed.)

**Comment by manikumaran1978** [comment]
yes please close
