### ISSUE TITLE
Footer Links

### ISSUE THREAD

**Issue by openwork** [magesuite/magesuite#61]
Hello there, I have just installed the magesuite and the default page has the this footer. I'm not able to figure out how do I make changes in the footer

![screenshot-beta joinmodicare com-2020 09 11-06_02_15](https://user-images.githubusercontent.com/5269510/92831958-b146d300-f3f4-11ea-86c6-9be142e68999.png)

**Comment by krzksz** [comment]
Hey, this should be helpful. It is a part of the documentation we are working on:
[CSHOP-41977775-110920-0834.pdf](https://github.com/magesuite/magesuite/files/5207736/CSHOP-41977775-110920-0834.pdf)
