### ISSUE TITLE
setup:di:compile fails - Class MageSuite\Discount\Helper\Discount does not exist

### ISSUE THREAD

**Issue by Flowlance** [magesuite/magesuite#62]
Hi. I'm trying to get magesuite 5.0.0 installed on a vanilla Magento 2.3.4 with php 7.2. The only module that is installed is Elasticsuite.

<img width="766" alt="Screenshot 2020-09-16 at 18 27 01" src="https://user-images.githubusercontent.com/3727974/93377500-5b8e8280-f85b-11ea-8927-c487cf0efb6a.png">

**Class MageSuite\Discount\Helper\Discount does not exist**

A workaround would be 
`composer require creativestyle/magesuite-discount`
However, this is a bug. Someone pointed out for me that this is the commit that broke it  https://github.com/magesuite/content-constructor-frontend/commit/61e5bbb87e7d0f10bdd9cf47dd9108fb35c5d595

**Comment by Alex7Lem** [comment]
Downgrading creativestyle/magesuite-content-constructor-frontend (v2.24.0 => v2.23.0)
composer require creativestyle/magesuite-content-constructor-frontend ~2.23.0

**Comment by diwipl** [comment]
Dear @Flowlance 

Thank you for submitting your issue.

We found out an issue we're having with github and packagist.org synchronisation. It caused some versions of packages to be not fully updated.

Please retry now, discount module should be installed and setup:di:compile should pass correctly.

**Comment by Flowlance** [comment]
> Dear @Flowlance
> 
> Thank you for submitting your issue.
> 
> We found out an issue we're having with github and packagist.org synchronisation. It caused some versions of packages to be not fully updated.
> 
> Please retry now, discount module should be installed and setup:di:compile should pass correctly.

Thank you. The issue seems to be solved now :)
