### ISSUE TITLE
Sample Data?

### ISSUE THREAD

**Issue by kolaente** [magesuite/magesuite#63]
Is there a package with sample data for the cms available?

**Comment by diwipl** [comment]
Hi,
Currently, we do not have any sample data package for CMS configuration.
What we do have if you'd like to see how components look like is sample page with components.
To see it go in admin to `Stores -> Configuration -> MageSuite -> Content Constructor` and set `Enable components list test page` to `Yes`.

Then you can access it using `contentconstructor/components/index` URL.

Example: https://demo.magesuite.io/contentconstructor/components/index/page/itbrowserwidth/

We use these pages for internal QA when we style shops
