### ISSUE TITLE
Composer error 

### ISSUE THREAD

**Issue by MaxTa91** [magesuite/magesuite#72]
I am having a problem when running the composer CMD 
Could not find a matching version of package creativestyle/magesuite^6.0.0.

**Comment by diwipl** [comment]
Please add space before `^6.0.0`

**Comment by MaxTa91** [comment]
Hi @diwipl 
Thank you so much. It works now. 
I have another problem when I run setup:upgrade Could you please help? I attached a screenshot at this message. 
![Screen Shot 2020-12-18 at 16 30 18](https://user-images.githubusercontent.com/11706605/102598360-7d472080-414e-11eb-9006-e22106bc9fa6.png)

**Comment by diwipl** [comment]
Seems like your elasticsearch setup is not done according to ElasticSuite documentation: https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x

You're missing plugins described in documentation.

**Comment by MaxTa91** [comment]
Thank you
