### ISSUE TITLE
JS Error in CMS Page

### ISSUE THREAD

**Issue by MaxTa91** [magesuite/magesuite#73]
I have an error when add a section in CMS page. Please help me :|
![Screen Shot 2020-12-18 at 17 00 35](https://user-images.githubusercontent.com/11706605/102601405-b41f3580-4152-11eb-99ed-954ae0f996e8.png)

**Comment by mborkowski** [comment]
Hi @MaxTa91,
Please see [#15](https://github.com/magesuite/magesuite/issues/15#issue-480099944) for a solution

**Comment by MaxTa91** [comment]
Thank you so much @mborkowski
