### ISSUE TITLE
Migrate CMS Content to Magesuite Component

### ISSUE THREAD

**Issue by tim-breitenstein-it** [magesuite/magesuite#74]
Is there a way to migrate the Magento 1.9 CMS page content to an Magesuite Component, Paragraph Component especially?

The old content is displayed without any style and can not be edited at the CMS page edit content.

**Comment by mborkowski** [comment]
Hi @tim-breitenstein-it ,
Unfortunately we don't have any migration tool for this kind of operations as we didn't need them so far. It would be difficult anyways as for CMS Blocks we now have both: Magento's standard editor + Content Constructor separately below `Content` panel.

**Comment by tim-breitenstein-it** [comment]
> we now have both: Magento's standard editor + Content Constructor separately below Content panel.

But there is no chance to edit this standard editor content?

**Comment by mborkowski** [comment]
Why not? 
You can use it just like before, it isi fully backwads compatible. You just have to remember about 2 things:

- It's implemented this way only for Static Blocks
- standard Content is a fallback now, so it will be shown as long as there's no module added to Content Constructor - in this case it will be replaced by this CC module. 

As you can see below for one of my projects based on MageSuite I use native Content for footer links and they're rendered properly (and will be until I add any CC module)

![Xnip2021-01-04_11-15-48](https://user-images.githubusercontent.com/7046321/103524773-66a70600-4e7e-11eb-92b5-1b1322cc3330.jpg)

**Comment by tim-breitenstein-it** [comment]
> Why not?
> You can use it just like before, it isi fully backwads compatible. You just have to remember about 2 things:
> 
> It's implemented this way only for Static Blocks
> standard Content is a fallback now, so it will be shown as long as there's no module added to Content Constructor - in this case it will be replaced by this CC module.
> As you can see below for one of my projects based on MageSuite I use native Content for footer links and they're rendered properly (and will be until I add any CC module)

I have migrated content in my CMS pages and the standard content editor is not visible at the CMS edit page so **I can´t see, remove or edit this old content**.

The old content is displayed fine at the frontend as long as I didn´t add any CC module.

So I need to move the old content to a Static Blocks and add this Static Blocks to the CSM page as a Paragraph Component?

**Comment by mborkowski** [comment]
Yes, so this is why I wrote that this suppoer of both apreaches is only available for **CMS Blocks**. For CMS Pages we didn't implement yet and I don't think we will. Old content is still there in your DB I think, so you can either do as you wrote, or - if you use this content only once and it's not reusable - move it directly to Paragraph Component within CMS Page's Content Constructor.

**Comment by frqnck** [comment]
For the CMS-page admin, it would be good to have a switcher to show the standard Content editor that would be useful during migration or when the standard facility is good enough.
