### ISSUE TITLE
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js' 

### ISSUE THREAD

**Issue by elnile** [magesuite/magesuite#81]
I'm on M2.4.1 showing this error and not able to add any items to the content container. 

require.js:1895 [Report Only] Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js' because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com secure.authorize.net test.authorize.net www.googleadservices.com www.google-analytics.com www.paypalobjects.com js.braintreegateway.com www.paypal.com geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.sandbox.paypal.com t.paypal.com s.ytimg.com video.google.com vimeo.com www.vimeo.com www.youtube.com *.payments-amazon.com *.payments-amazon.co.uk *.payments-amazon.co.jp *.payments-amazon.jp *.payments-amazon.it *.payments-amazon.fr *.payments-amazon.es www.apptrian.com api.stripe.com js.stripe.com m.stripe.com x.klarnacdn.net klarna.com na.playground.klarnaevt.com eu.playground.klarnaevt.com klarna-payments-eu.playground.klarna.com klarna-payments-na.playground.klarna.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

req.load @ require.js:1895
require.js:1895 [Report Only] Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/vue-resource/0.9.3/vue-resource.js' because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com secure.authorize.net test.authorize.net www.googleadservices.com www.google-analytics.com www.paypalobjects.com js.braintreegateway.com www.paypal.com geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.sandbox.paypal.com t.paypal.com s.ytimg.com video.google.com vimeo.com www.vimeo.com www.youtube.com *.payments-amazon.com *.payments-amazon.co.uk *.payments-amazon.co.jp *.payments-amazon.jp *.payments-amazon.it *.payments-amazon.fr *.payments-amazon.es www.apptrian.com api.stripe.com js.stripe.com m.stripe.com x.klarnacdn.net klarna.com na.playground.klarnaevt.com eu.playground.klarnaevt.com klarna-payments-eu.playground.klarna.com klarna-payments-na.playground.klarna.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

req.load @ require.js:1895
14content-constructor.ts:340 Uncaught TypeError: Cannot read property 'defaults' of undefined
    at VueComponent.getComponentConfigurator (content-constructor.ts:340)
    at VueComponent.<anonymous> (vue.js:220)
    at VueComponent.onPickComponent (component-picker.ts:115)
    at VueComponent.onPickComponent (vue.js:220)
    at VueComponent.eval (eval at Lt (vue.min.js:1), <anonymous>:3:15)
    at HTMLAnchorElement.n (vue.js:8250)
    at HTMLAnchorElement.<anonymous> (vue.js:5047)
content-constructor.ts:340 Uncaught TypeError: Cannot read property 'defaults' of undefined
    at VueComponent.getComponentConfigurator (content-constructor.ts:340)
    at VueComponent.<anonymous> (vue.js:220)
    at VueComponent.onPickComponent (component-picker.ts:115)
    at VueComponent.onPickComponent (vue.js:220)
    at VueComponent.eval (eval at Lt (vue.min.js:1), <anonymous>:3:15)
    at HTMLAnchorElement.n (vue.js:8250)
    at HTMLAnchorElement.<anonymous> (vue.js:5047)
getComponentConfigurator @ content-constructor.ts:340
(anonymous) @ vue.js:220
onPickComponent @ component-picker.ts:115
(anonymous) @ vue.js:220
eval @ VM27397:3
n @ vue.js:8250
(anonymous) @ vue.js:5047

**Comment by userz58** [comment]
![error1](https://user-images.githubusercontent.com/2612186/107387780-36e6c000-6b06-11eb-9e7f-8154ebb23eaa.jpg)
![error2](https://user-images.githubusercontent.com/2612186/107387785-38b08380-6b06-11eb-8571-f56dabc65f63.jpg)

**Comment by mborkowski** [comment]
Hello,
I'm not sure about the content security policy issue, we'd need to check this. However it seems Vue works fine as app is running. Regarding second one, please try https://github.com/magesuite/magesuite/issues/15

**Comment by userz58** [comment]
@mborkowski, thanks a lot!

**Comment by backendorf** [comment]
Helo! I have creted a fix module with the csp_whitelist.xml file. This solve the load problem, but "Uncaught TypeError: Cannot read property 'defaults' of undefined" persists. File content:
`<?xml version="1.0"?>
<csp_whitelist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Csp:etc/csp_whitelist.xsd">
    <policies>
        <policy id="script-src">
            <values>
                <value id="vue" type="host">https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js</value>
                <value id="vue-resource" type="host">https://cdnjs.cloudflare.com/ajax/libs/vue-resource/0.9.3/vue-resource.js</value>
            </values>
        </policy>
    </policies>
</csp_whitelist>
`

**Comment by mborkowski** [comment]
Hi @DaviBackendorf 
Have you seen my previous answer? It is required to set theme on the website level, otherwise our collector won't be able to get default settings from etc/view.xml. Please make sure you have it setup according to #15
