### ISSUE TITLE
youtube video on the product page does not work

### ISSUE THREAD

**Issue by redati** [magesuite/magesuite#82]
Magento 2.4.1 php7.4

When uploading youtube video to the product, the video thumbnail appears but the video does not play.

**Comment by mborkowski** [comment]
Hello,
Thos doesn't seem to be related to Mageasuite as we didn't customize anything beside CSS and a template (just to add a fallback) in the gallery area.
Are you aure your youtube API keys are configured properly in admin panel as described in Magento documentation?
If yes, could you please also try to switch to luma and check this issue on luma theme?

**Comment by redati** [comment]
Yes, when disabling the megapack, everything works fine. It stops working only with megapack enabled. I have a standard theme.

**Comment by redati** [comment]
It seems that the scripts needed to run the video are not loaded.

I even added a product with a "--product-url =" video, but it didn't work.

There is no error on the console.

**Comment by redati** [comment]
yes, luma.

**Comment by drabikowy** [comment]
@redati Could you please describe what error do you have in the console (if any)? 
We faced an issue with magepack only when there were no dependencies defined correctly for some modules and the order of loading modules was kind of random. With magepack disabled, issue was not present as I assume the order was different (randomly correct).

**Comment by redati** [comment]
no error on the console, the play button also does not appear with an active module.

**Comment by redati** [comment]
update, fix in now https://github.com/magento/magento2/pull/32499

**Comment by ihor-sviziev** [comment]
@redati, thx for mentioning my PR. I didn't know that someone else had this issue. I linked this issue in the PR.
For now, you could apply changes from my PR as a patch.

**Comment by mborkowski** [comment]
Thanks @ihor-sviziev for your feedback and contribution to Magento.
We will definitely won't patch it on our side, it suppose to be fixed on Magento side and all we can do is wait for this fix to be released. Otherwise we will end up with trash in our packages.
If somebody need this asap, feel free to customize on your side ;)

**Comment by redati** [comment]
> @redati , obrigado por mencionar meu PR. Eu não sabia que outra pessoa tinha esse problema. Liguei esse assunto no PR.
> Por enquanto, você pode aplicar as alterações do meu PR como um patch.

Yes, it's been a while. I applied the correction and it worked. Thanks. Success for you.
