### ISSUE TITLE
Support for hyvä

### ISSUE THREAD

**Issue by tmotyl** [magesuite/magesuite#89]
Hi
Are you planning to support hyvä theme in rendering?

**Comment by mborkowski** [comment]
Hi @tmotyl,
No, since our builder has assumptions that theme must match and especially in the area of CSS they are pretty far from Magento requirements

**Comment by frqnck** [comment]
As you likely know, Hyvä relies on Tailwind CSS (functional CSS) and Alpines.js

Magesuite strength is its CSS. Its weakness, it that it relies mostly on the Magento 2 ’s JS stack — although improving many aspect of it...

The RequireJs, jQuery and Knockout trio always needed to be ditched (that combo was already out of date when Magento first released it). Alpinejs or any lightweight equivalent makes a lot of sense...

I haven’t had access to the Hyvä source code yet — it is not fully open source and require a license to even review the code 👎 but it seems to me that the Hyvä Blank/Reset theme is not far off from the Magesuite approach. I don’t know as this stage how components are maintained/glued together (typescript or not..). However, the same pattern that Magesuite currently employ could be reapply with Alpine too e.g. [Alpine typescript](https://github.com/LeanAdmin/alpine-typescript). 

Just food for thought. Magesuite would benefit from the cohesion and cherry picking parts out of Hyvä...

**Comment by tmotyl** [comment]
I'm not looking for a out of the box solution for hyva, its not a problem for me to add new templates/styles for custom blocks from magesuite.
My main pain point is that magesuite is tightly coupled with magento default theme and it forces you to inherit theme from magesuite.
I believe the first step would be to allow to create magesuite frontend theme independently from luma. so I can create my own theme from scratch.

**Comment by mborkowski** [comment]
Yeah, so on our roadmap for the future is to make at least content constructor packagages independant from theme, but it's long way out and it's not the priority (yet)

**Comment by frqnck** [comment]
> I believe the first step would be to allow to create magesuite frontend theme independently from luma. so I can create my own theme from scratch.

Magesuite FE does not rely on Luma – it starts with Blank and reset 99% of its CSS then remove/reset RequiresJs, etc.
Hyvä does the same but goes a step further by removing the whole JS stack...

**Comment by mborkowski** [comment]
There's this always-true dependency: the more custom things you do, the more you'll have to maintain. Currently we see more benefit developing features Magento way - usimg widgets and uiComponents. We all know this Magento FE stack is "a bit" outdated, but we still holding on to Magento and therefore we must accept its stack as well.
