### ISSUE TITLE
Menu in mobile version not visible. ( bug in mobile version ) #70

### ISSUE THREAD

**Issue by onsite12** [magesuite/magesuite#90]
When I click the hamburger icon on the mobile version the menu is not visible. I only see the login function + option to change currency.

Running Magento 2.4.1
How to solve this?
![image](https://user-images.githubusercontent.com/82204564/115190568-84744000-a0e8-11eb-8c57-ec911636822c.png)

This option is on:
![image](https://user-images.githubusercontent.com/82204564/115190589-8d651180-a0e8-11eb-9d0a-4132d69f16a8.png)

**Comment by mborkowski** [comment]
Hi @onsite12,
There has to be an error in the console, for some reason it didn't fetch via ajax

**Comment by onsite12** [comment]
Looks like there was an error in the database. The include in mobile navigation field was empty. I solved it by turning it off, saving it, turning it on. Thanks for help.
