### ISSUE TITLE
YARN DOING NOTHING

### ISSUE THREAD

**Issue by kornblumenapotheke** [magesuite/magesuite#91]
Hello 
yarn returns 00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

Any ideas?

**Comment by mborkowski** [comment]
Hello. Seems like it's issue on your side. According to some similar reports this issue pops up if you're using wrong yarn installation (mostly on linux)

**Comment by janssensjelle** [comment]
I installed yarn via apt and got this error. If you do the command below, it should work
`npm install --global yarn`

**Comment by drabikowy** [comment]
I'm closing this issue, this is not related to MageSuite code itself.
Best regards
