### ISSUE TITLE
Sales orders - sanitized after installing Magesuite

### ISSUE THREAD

**Issue by Green2Matter** [magesuite/magesuite#92]
Recently I've installed on my test VM the latest and greatest ver. 2.4.2-p1. I did a few test orders and I couldn't find a reason why, when being logged in as admin with theoretically full permissions, sales orders are sanitized with asterisks: 
<img width="863" alt="Adddresses" src="https://user-images.githubusercontent.com/71682684/118657092-73a01280-b7eb-11eb-9ccb-a5f63c87bacd.png">
If I try to edit them I'm given information: `Access Denied You don't have permision to view`
I realized that I have installed Magesuite 7.0.0. At first I disabled all Elasticsuite's modules and nothing changed. After disabling Magesuite's modules all came back to normal. I don't know which exactly module is responsible for this error.
To confirm that I installed second instance of Magento and it was exactly the same...
Is it something you know about?

**Comment by diwipl** [comment]
Yes, that's a default GDPR related protection. There are two methods of disabling it:
- Create a new admin role that has "Hide customer data" permission unchecked
- Disable/remove MageSuite_Gdpr module

**Comment by Green2Matter** [comment]
Thanks, all is clear now!
